### ISSUE TITLE
Feature request: Differentiate the color of the folder nodes from the default tag node color

### ISSUE THREAD

**Issue by aonyym** [ratibus11/folders2graph#8]
Could be achieved by asserting another type of node, adding the css property or adding a custom class one could modify. Maybe the color could even be configurable in the plugin files.

I tried to modify your code myself but didn't get far as the plugin wouldn't load and I could debug the canvas.

Anyway, great work with the plugin, I think it's a wonderful addition to obsidian.

**Comment by ratibus11** [comment]
Hi!
I tried to inspect the Obsidian runtime code and haven't been able to find a way to create new nodes kind or edit existing ones. I think that part is deep enough to not be editable from the outside.

I know this is a bit frustrating because it can be confusing with real tag nodes, but that is the only solution I found for now.
