### ISSUE TITLE
Question: How to modify the plugin to only name the nested folder nodes after themselves and not the whole path

### ISSUE THREAD

**Issue by linuzzx** [ratibus11/folders2graph#9]
I don't need an implementation, just wanna know what to change in the TS/JS

**Comment by ratibus11** [comment]
Hi!
As far as I understand about how Obsdian does work, you can't "just" only keep the current folder's name, because Obsidian needs each tag node to have a unique name.
So if your tag nodes (the folders) are `foo/c` and `bar/c` and you only keep the folder's name, you will have 2 `c` tag nodes, which will be merged as a single one in the graph 😢

I'm managing the folder list from line 78 to 88 in [`Main.ts`](https://github.com/ratibus11/folders2graph/blob/master/src/Main.ts#L102). For all files nodes, I get all of its parent's full path (eg. for file `a/b/c/foo.md`, I get `/`, `/a`, `/a/b` and `/a/b/c`) and store them in a [`Set`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set), as each one must be unique. Then, I link each file node to it's nearest "folder" node.
